# Generated by Django 4.0.4 on 2022-05-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('short_name', models.CharField(max_length=20, verbose_name='short name ')),
                ('Anulate', models.BooleanField(default=False, verbose_name='Anulate')),
            ],
        ),
    ]
