# Generated by Django 4.0.4 on 2022-05-25 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departmen',
            new_name='Department',
        ),
    ]
