# Generated by Django 4.0.4 on 2022-05-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_rename_departmen_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='short name '),
        ),
    ]
