# Generated by Django 4.0.4 on 2022-05-26 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_department_short_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-name'], 'verbose_name': 'my department'},
        ),
    ]
