# Generated by Django 4.0.4 on 2022-05-26 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_alter_department_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'short_name')},
        ),
    ]
