# Generated by Django 4.0.4 on 2022-05-25 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0003_alter_department_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('job', models.CharField(choices=[('1', 'ADMINISTRADOR'), ('3', 'OTRO'), ('0', 'CONTADOR'), ('2', 'ECONOMISTA')], max_length=1, verbose_name='job')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
        ),
    ]
