# Generated by Django 4.0.4 on 2022-05-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_employee_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.CharField(choices=[('3', 'OTRO'), ('0', 'CONTADOR'), ('2', 'ECONOMISTA'), ('1', 'ADMINISTRADOR')], max_length=1, verbose_name='job'),
        ),
    ]
