# Generated by Django 4.0.4 on 2022-05-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_alter_employee_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.CharField(max_length=50, verbose_name='ability')),
            ],
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-first_name', 'last_name'], 'verbose_name': 'possible jobs'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.CharField(choices=[('0', 'CONTADOR'), ('1', 'ADMINISTRADOR'), ('2', 'ECONOMISTA'), ('3', 'OTRO')], max_length=1, verbose_name='job'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('first_name', 'last_name')},
        ),
    ]
