# Generated by Django 4.0.4 on 2022-05-27 01:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_alter_employee_options_alter_skills_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-first_name', 'last_name', '-job'], 'verbose_name': 'my employee'},
        ),
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='curriculum_vitae',
            field=ckeditor.fields.RichTextField(default='text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(to='person.skills'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.CharField(choices=[('3', 'OTRO'), ('2', 'ECONOMISTA'), ('1', 'ADMINISTRADOR'), ('0', 'CONTADOR')], max_length=1, verbose_name='job'),
        ),
    ]
