# Generated by Django 4.0.4 on 2022-05-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_alter_employee_options_employee_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Full name '),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.CharField(choices=[('3', 'OTRO'), ('1', 'ADMINISTRADOR'), ('2', 'ECONOMISTA'), ('0', 'CONTADOR')], max_length=1, verbose_name='job'),
        ),
    ]
